### ISSUE TITLE
Add support for extra hugo fields to be setup by extra bibtex fields. 

### ISSUE THREAD

**Issue by lrnv** [wowchemy/bibtex-to-markdown#125] opened 2023-10-30 09:35 UTC
Hey, 

Bacisally the `url_XXX` fields from hugo could be filled directly by corresponding `hugo_url_XXX` fields in the bibtex. Recall that bibtex allows for any field to be defined. 

Moreover, this will not stop the bib file to be used for any other purposes as those filds would simply be ignored by reference managers that do not know them.

**Comment by gcushen** [comment] 2023-10-30 20:46
Closing as it appears to be a duplicate of the existing issue #48 . Feel free to contribute to that issue. First we need to decide a strategy for mapping attributes. E.g. how would you represent nested page options like image > caption.

**Closed by gcushen** 2023-10-30 20:46 UTC
